version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    networks:
      - develop-network

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - develop-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - develop-network

  queue:
    build:
      context: .
      dockerfile: './src/config/docker/queue.dockerfile'
    working_dir: /usr/src/jobs
    command: yarn queue
    volumes:
      - .:/usr/src
    networks:
      - develop-network
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: './src/config/docker/node.dockerfile'
    command: yarn dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - develop-network
    depends_on:
      - db
      - mongo
      - redis

networks:
  develop-network:
    driver: bridge
