version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    networks:
      - develop-network

  app:
    build:
      context: .
      dockerfile: './src/config/docker/node.dockerfile'
    command: yarn dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - develop-network
    depends_on:
      - db

networks:
  develop-network:
    driver: bridge
